-- Insert Team Building and Expert Accountant Tax Deduction Rules
INSERT INTO public.tax_deduction_rules (
  category, deduction_name, max_amount, max_amount_description, can_be_increased, 
  increase_conditions, increase_amounts, proof_required, applicable_forms, 
  business_types, tax_year, notes, irs_reference, display_order
) VALUES
-- Team Building / Company Events (100% deductible)
('team_building', 'Company-Wide Holiday Party', NULL, 'No limit - 100% deductible', false, 
  NULL, NULL, 
  ARRAY['Guest list showing all employees invited', 'Receipts for venue, food, entertainment', 'Photos or documentation of event', 'Date and business purpose'],
  ARRAY['Schedule C', 'Form 1120', 'Form 1120-S', 'Form 1065'],
  ARRAY['All business types'],
  2024, 
  '100% deductible when ALL employees are invited. Must be infrequent and occasional. Cannot exclude certain employees.', 
  'IRC Section 274(e)(4)', 1),

('team_building', 'Company Picnic/Summer Event', NULL, 'No limit - 100% deductible', false, 
  NULL, NULL, 
  ARRAY['Invitation showing all employees', 'Receipts', 'Event photos'],
  ARRAY['Schedule C', 'Form 1120', 'Form 1120-S', 'Form 1065'],
  ARRAY['All business types'],
  2024, 
  'Company outings for all employees are 100% deductible. Food, activities, venue all qualify.', 
  'IRC Section 274(e)(4)', 2),

('team_building', 'Team Building Activities with Meals', NULL, 'No limit - 100% if meal is integral', true, 
  ARRAY['Meal is integral to the team activity', 'Activity has clear business purpose', 'All team members invited'],
  '{"integral_meal": "100% deductible", "separate_meal": "50% deductible"}'::jsonb,
  ARRAY['Activity description and business purpose', 'Receipts itemized', 'Attendee list', 'Documentation showing meal was part of activity'],
  ARRAY['Schedule C', 'Form 1120', 'Form 1120-S', 'Form 1065'],
  ARRAY['All business types'],
  2024, 
  'KEY TIP: When meal is INTEGRAL to team building (e.g., cooking class, escape room with catered lunch), entire cost is 100% deductible. Separate meals at restaurants are 50%.', 
  'IRC Section 274(e)(4), (n)', 3),

('team_building', 'Employee Achievement Awards', 5000, 'Per employee per year for qualified plan awards', true, 
  ARRAY['Award is part of qualified plan', 'Written criteria established before award'],
  '{"non_qualified": 1600, "qualified_plan": 5000}'::jsonb,
  ARRAY['Written award plan', 'Employee records', 'Purchase receipts'],
  ARRAY['Schedule C', 'Form 1120', 'Form 1120-S'],
  ARRAY['All business types'],
  2024, 
  'Tangible personal property awards (not cash). Up to $1,600 without qualified plan, $5,000 with qualified plan.', 
  'IRC Section 274(j)', 4),

-- Charitable/Donation Rules for Vine Products
('donations', 'Donated Inventory - Vine Products', NULL, 'Generally limited to cost basis (often $0 for Vine)', true, 
  ARRAY['Donating to qualified charity for ill, needy, or infants', 'C-Corp making qualified contributions'],
  '{"standard": "Cost basis", "enhanced_c_corp": "Basis + 50% of FMV appreciation (up to 2x basis)"}'::jsonb,
  ARRAY['Form 8283 for items over $500', 'Written acknowledgment from charity', 'Fair market value appraisal if over $5,000', 'Contemporaneous written record'],
  ARRAY['Schedule C', 'Form 1040 Schedule A', 'Form 1120'],
  ARRAY['All business types'],
  2024, 
  'IMPORTANT: For Vine products, your cost basis is $0 since you paid nothing. Deduction is generally limited to basis. Enhanced deduction available for C-Corps donating to qualified organizations.', 
  'IRC Section 170(e)(3)', 5),

('donations', 'Donation Documentation Requirements', NULL, 'Must have proper documentation', false, 
  NULL, NULL,
  ARRAY['Under $250: Receipt or written record', '$250-$500: Written acknowledgment from charity', '$500-$5,000: Form 8283 Section A', 'Over $5,000: Qualified appraisal + Form 8283 Section B'],
  ARRAY['Form 8283', 'Schedule A', 'Schedule C'],
  ARRAY['All business types'],
  2024, 
  'Documentation is CRITICAL. No documentation = no deduction. Get written acknowledgment BEFORE filing.', 
  'IRC Section 170(f)(8)', 6),

-- Rental Equipment Business Specific
('rental_business', 'Startup Costs - First Year', 5000, 'Immediate deduction up to $5,000', true, 
  ARRAY['Total startup costs under $50,000', 'Remaining costs amortized over 180 months'],
  '{"under_50k": 5000, "50k_to_55k": "Reduced dollar-for-dollar", "over_55k": 0}'::jsonb,
  ARRAY['Receipts for all startup expenses', 'Business plan documentation', 'Market research costs', 'Legal and accounting fees'],
  ARRAY['Schedule C', 'Form 4562'],
  ARRAY['Sole proprietor', 'Single-member LLC', 'Partnership', 'S-Corp'],
  2024, 
  'Immediate $5,000 deduction for startup costs if total under $50,000. Excess amortized over 180 months.', 
  'IRC Section 195', 10),

('rental_business', 'Repairs vs. Improvements - De Minimis Safe Harbor', 2500, 'Per invoice/item for no AFS businesses', true, 
  ARRAY['Have applicable financial statements (AFS)', 'Make annual election'],
  '{"no_afs": 2500, "with_afs": 5000}'::jsonb,
  ARRAY['Invoice for each item', 'Election statement', 'Written capitalization policy'],
  ARRAY['Schedule C', 'Form 1120', 'Form 1120-S'],
  ARRAY['All business types'],
  2024, 
  'EXPERT TIP: Items costing $2,500 or less per invoice can be immediately expensed. No need to depreciate. Make the election annually.', 
  'Treas. Reg. 1.263(a)-1(f)', 11),

('rental_business', 'Small Taxpayer Safe Harbor - Building Repairs', 10000, 'Per building per year', true, 
  ARRAY['Unadjusted basis of building is $1M or less', 'Average gross receipts under $10M'],
  '{"under_10k_or_2_percent": "Fully deductible as repair"}'::jsonb,
  ARRAY['Building records showing basis', 'Repair invoices', 'Annual election'],
  ARRAY['Schedule C', 'Schedule E', 'Form 1120'],
  ARRAY['Rental businesses', 'Real estate investors'],
  2024, 
  'Deduct repairs up to $10,000 or 2% of building basis (whichever is less) without proving they are repairs vs. improvements.', 
  'Treas. Reg. 1.263(a)-3(h)', 12),

('rental_business', 'Listed Property - Mixed Use Equipment', NULL, 'Based on business use percentage', true, 
  ARRAY['Business use exceeds 50%', 'Detailed usage log maintained'],
  '{"over_50_percent": "Section 179 and bonus eligible", "under_50_percent": "Straight-line depreciation only"}'::jsonb,
  ARRAY['Daily/weekly usage log', 'Mileage records for vehicles', 'Time logs for equipment', 'Business purpose documentation'],
  ARRAY['Form 4562', 'Schedule C'],
  ARRAY['All business types'],
  2024, 
  'Equipment used for both personal and business (cameras, computers, vehicles) must track usage. Over 50% business use unlocks better deductions.', 
  'IRC Section 280F', 13),

-- Expert Accountant Tips
('expert_tips', 'Accountable Plan for Reimbursements', NULL, 'Unlimited tax-free reimbursements', false, 
  NULL, NULL,
  ARRAY['Written accountable plan policy', 'Business connection documented', 'Timely expense reports (60 days)', 'Return of excess (120 days)'],
  ARRAY['Schedule C', 'Form 1120', 'Form 1120-S'],
  ARRAY['All business types'],
  2024, 
  'EXPERT TIP: Reimburse yourself/employees tax-free for business expenses through an accountable plan. Not taxable income to recipient.', 
  'IRC Section 62(c)', 20),

('expert_tips', 'Augusta Rule - Rent Your Home', NULL, 'Up to 14 days tax-free', false, 
  NULL, NULL,
  ARRAY['Board meeting minutes', 'Rental agreement', 'Fair market rent documentation (comparable venues)', 'Business purpose documentation'],
  ARRAY['Schedule C', 'Form 1120', 'Form 1120-S'],
  ARRAY['S-Corp', 'C-Corp', 'Partnership'],
  2024, 
  'EXPERT TIP: Rent your home to your business for meetings up to 14 days/year. Tax-free income to you, deductible expense to business.', 
  'IRC Section 280A(g)', 21),

('expert_tips', 'Hire Your Children', 12950, 'Standard deduction amount - tax-free to child', true, 
  ARRAY['Child under 18 and sole proprietor/partnership (parents only)', 'Legitimate work performed', 'Reasonable wages for work type'],
  '{"under_18_sole_prop": "No FICA taxes", "under_21": "No FUTA", "any_age": "Deductible as wages"}'::jsonb,
  ARRAY['Time sheets', 'Job description', 'W-4 on file', 'Reasonable wage documentation'],
  ARRAY['Schedule C', 'Form 1120-S'],
  ARRAY['Sole proprietor', 'Single-member LLC'],
  2024, 
  'EXPERT TIP: Pay children for legitimate work. Under 18 in sole prop = no FICA. Their income up to standard deduction is tax-free.', 
  'IRC Section 3121(b)(3)(A)', 22),

('expert_tips', 'S-Corp Reasonable Salary Strategy', NULL, 'Save 15.3% SE tax on distributions', true, 
  ARRAY['Pay reasonable salary first', 'Document salary comparables', 'Take remaining profits as distributions'],
  '{"savings": "15.3% SE tax on distribution portion"}'::jsonb,
  ARRAY['Salary survey documentation', 'Job description', 'Comparable wage data', 'Payroll records'],
  ARRAY['Form 1120-S', 'Form W-2'],
  ARRAY['S-Corp', 'LLC taxed as S-Corp'],
  2024, 
  'EXPERT TIP: S-Corp owners save SE tax on profits taken as distributions (not salary). Must pay reasonable salary first.', 
  'IRC Section 1366', 23),

('expert_tips', 'Maximize Retirement Contributions', 69000, 'Total 401(k) contributions 2024', true, 
  ARRAY['Have self-employment income', 'Set up Solo 401(k) or SEP-IRA before year end'],
  '{"employee_contribution": 23000, "catch_up_over_50": 7500, "employer_contribution": "25% of compensation"}'::jsonb,
  ARRAY['Plan documents', 'Contribution records', 'Bank statements'],
  ARRAY['Schedule C', 'Form 1040'],
  ARRAY['Sole proprietor', 'Single-member LLC', 'S-Corp'],
  2024, 
  'EXPERT TIP: Solo 401(k) allows $23K employee + 25% employer contributions. Reduces SE income AND income tax.', 
  'IRC Section 401(k), 404', 24),

('expert_tips', 'Entity Selection - LLC vs S-Corp', NULL, 'Break-even typically $40-60K net income', false, 
  NULL, NULL,
  ARRAY['Net income projections', 'Reasonable salary analysis', 'State tax considerations'],
  ARRAY['Form 2553', 'Form 1120-S'],
  ARRAY['Single-member LLC', 'Partnership'],
  2024, 
  'EXPERT TIP: When net SE income exceeds ~$40-60K, S-Corp election often saves money. Calculate break-even including S-Corp costs.', 
  'IRC Section 1362', 25),

('expert_tips', 'Bunching Deductions Strategy', NULL, 'Alternate standard/itemized years', false, 
  NULL, NULL,
  ARRAY['Multi-year projection of deductions', 'Timing documentation'],
  ARRAY['Schedule A', 'Form 1040'],
  ARRAY['All business types'],
  2024, 
  'EXPERT TIP: Bunch charitable contributions, property taxes, medical into alternating years to exceed standard deduction some years.', 
  'IRC Section 63', 26),

-- Meals - Additional Expert Rules
('meals', 'Meals During Overnight Travel', NULL, '50% of actual or per diem', true, 
  ARRAY['Use per diem rates instead of actual receipts'],
  '{"actual": "50% of receipts", "per_diem": "50% of GSA rate - no receipts needed"}'::jsonb,
  ARRAY['Travel itinerary', 'Business purpose', 'Receipts OR per diem election'],
  ARRAY['Schedule C', 'Form 2106'],
  ARRAY['All business types'],
  2024, 
  'EXPERT TIP: Use per diem rates to simplify - no need to keep meal receipts. Just track location and dates.', 
  'IRC Section 274(n), Rev Proc 2019-48', 30),

-- Back Taxes / Amended Returns
('back_taxes', 'Amended Return - Claim Missed Deductions', NULL, 'Within 3 years of filing or 2 years of payment', false, 
  NULL, NULL,
  ARRAY['Original return', 'Supporting documentation for new deductions', 'Form 1040-X'],
  ARRAY['Form 1040-X', 'Form 1120-X'],
  ARRAY['All business types'],
  2024, 
  'CRITICAL: You have 3 years from original filing date to amend and claim missed deductions. Do NOT let this expire!', 
  'IRC Section 6511', 40),

('back_taxes', 'Net Operating Loss (NOL) Carryforward', NULL, '80% of taxable income limit', true, 
  ARRAY['Farming losses', 'Certain disaster losses'],
  '{"standard": "80% of taxable income", "farming": "Can carryback 2 years"}'::jsonb,
  ARRAY['Tax returns showing loss', 'Form 172', 'Loss calculations'],
  ARRAY['Form 1040', 'Schedule C', 'Form 1120'],
  ARRAY['All business types'],
  2024, 
  'If you had business losses, they can offset 80% of future taxable income. Carry forward indefinitely. Farm losses can carry back 2 years.', 
  'IRC Section 172', 41),

('back_taxes', 'IRS Installment Agreement', NULL, 'Pay over time if you owe', false, 
  NULL, NULL,
  ARRAY['Form 9465', 'Financial disclosure if over $50K', 'Bank statements'],
  ARRAY['Form 9465', 'Form 433-D'],
  ARRAY['All business types'],
  2024, 
  'Cannot pay in full? Set up installment plan. Under $50K can be done online. Interest accrues but penalties reduced.', 
  'IRC Section 6159', 42);

-- Update category labels in a separate helper query
-- Add 2025 versions of key rules that are changing
INSERT INTO public.tax_deduction_rules (
  category, deduction_name, max_amount, max_amount_description, can_be_increased, 
  increase_conditions, increase_amounts, proof_required, applicable_forms, 
  business_types, tax_year, notes, irs_reference, display_order
) VALUES
('depreciation', 'Bonus Depreciation - 2025 Rate', NULL, '40% first-year bonus (phasing out)', false, 
  NULL, '{"2024": "60%", "2025": "40%", "2026": "20%", "2027": "0%"}'::jsonb,
  ARRAY['Purchase receipts', 'Placed in service date', 'Form 4562'],
  ARRAY['Form 4562', 'Schedule C'],
  ARRAY['All business types'],
  2025, 
  'Bonus depreciation continues phasing out. 2025 = 40%. Plan major purchases accordingly.', 
  'IRC Section 168(k)', 2);
