-- Add state column to track state-specific fields
ALTER TABLE public.irs_form_field_definitions 
ADD COLUMN IF NOT EXISTS state_code text DEFAULT NULL;

-- Create state tax forms reference table
CREATE TABLE public.state_tax_forms (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  state_code text NOT NULL,
  state_name text NOT NULL,
  form_type text NOT NULL, -- 'individual', 'business', 'withholding'
  form_number text NOT NULL,
  form_name text NOT NULL,
  filing_deadline text,
  extension_deadline text,
  has_local_tax boolean DEFAULT false,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE(state_code, form_number)
);

-- Enable RLS
ALTER TABLE public.state_tax_forms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view state tax forms"
ON public.state_tax_forms FOR SELECT USING (true);

CREATE POLICY "Admins can manage state tax forms"
ON public.state_tax_forms FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- Insert Form 1040 field definitions
INSERT INTO public.irs_form_field_definitions (form_type, field_name, field_label, field_type, max_length, is_required, irs_box_number, description, display_order) VALUES
-- Filing Status
('1040', 'filing_status', 'Filing Status', 'enum', 1, true, NULL, '1=Single, 2=MFJ, 3=MFS, 4=HOH, 5=QW', 1),
-- Taxpayer Info
('1040', 'first_name', 'First Name', 'text', 40, true, NULL, 'Your first name', 2),
('1040', 'middle_initial', 'Middle Initial', 'text', 1, false, NULL, 'Middle initial', 3),
('1040', 'last_name', 'Last Name', 'text', 40, true, NULL, 'Your last name', 4),
('1040', 'ssn', 'Social Security Number', 'text', 9, true, NULL, '9-digit SSN', 5),
('1040', 'spouse_first_name', 'Spouse First Name', 'text', 40, false, NULL, 'Spouse first name if MFJ', 6),
('1040', 'spouse_middle_initial', 'Spouse Middle Initial', 'text', 1, false, NULL, 'Spouse middle initial', 7),
('1040', 'spouse_last_name', 'Spouse Last Name', 'text', 40, false, NULL, 'Spouse last name', 8),
('1040', 'spouse_ssn', 'Spouse SSN', 'text', 9, false, NULL, 'Spouse SSN if MFJ', 9),
('1040', 'address_line1', 'Home Address', 'text', 40, true, NULL, 'Street address', 10),
('1040', 'address_line2', 'Apartment No.', 'text', 10, false, NULL, 'Apt number', 11),
('1040', 'city', 'City', 'text', 25, true, NULL, 'City name', 12),
('1040', 'state', 'State', 'text', 2, true, NULL, '2-letter state code', 13),
('1040', 'zip', 'ZIP Code', 'text', 9, true, NULL, 'ZIP code', 14),
('1040', 'foreign_country', 'Foreign Country', 'text', 40, false, NULL, 'If foreign address', 15),
('1040', 'foreign_province', 'Foreign Province', 'text', 40, false, NULL, 'Foreign province/state', 16),
('1040', 'foreign_postal_code', 'Foreign Postal Code', 'text', 20, false, NULL, 'Foreign postal code', 17),
-- Presidential Campaign
('1040', 'presidential_campaign_you', 'Presidential Campaign (You)', 'boolean', NULL, false, NULL, 'Check if you want $3 to go to fund', 18),
('1040', 'presidential_campaign_spouse', 'Presidential Campaign (Spouse)', 'boolean', NULL, false, NULL, 'Check if spouse wants $3 to fund', 19),
-- Digital Assets
('1040', 'digital_assets', 'Digital Assets Question', 'boolean', NULL, true, NULL, 'Did you receive/sell/exchange digital assets?', 20),
-- Dependents
('1040', 'dependent_1_name', 'Dependent 1 Name', 'text', 80, false, NULL, 'First and last name', 21),
('1040', 'dependent_1_ssn', 'Dependent 1 SSN', 'text', 9, false, NULL, 'Dependent SSN', 22),
('1040', 'dependent_1_relationship', 'Dependent 1 Relationship', 'text', 20, false, NULL, 'Relationship to you', 23),
('1040', 'dependent_1_ctc', 'Dependent 1 Child Tax Credit', 'boolean', NULL, false, NULL, 'Qualifies for CTC', 24),
('1040', 'dependent_1_odc', 'Dependent 1 Other Dependent Credit', 'boolean', NULL, false, NULL, 'Qualifies for ODC', 25),
-- Income Lines
('1040', 'wages_salaries_tips', 'Wages, Salaries, Tips', 'numeric', NULL, false, 'Line 1a', 'W-2 Box 1 total', 30),
('1040', 'household_employee_wages', 'Household Employee Wages', 'numeric', NULL, false, 'Line 1b', 'Wages not on W-2', 31),
('1040', 'tip_income', 'Tip Income', 'numeric', NULL, false, 'Line 1c', 'Tips not on W-2', 32),
('1040', 'medicaid_waiver', 'Medicaid Waiver Payments', 'numeric', NULL, false, 'Line 1d', 'Excludable payments', 33),
('1040', 'dependent_care_benefits', 'Dependent Care Benefits', 'numeric', NULL, false, 'Line 1e', 'From Form 2441', 34),
('1040', 'adoption_benefits', 'Employer Adoption Benefits', 'numeric', NULL, false, 'Line 1f', 'From Form 8839', 35),
('1040', 'form_8919_wages', 'Form 8919 Wages', 'numeric', NULL, false, 'Line 1g', 'Uncollected SS/Medicare', 36),
('1040', 'other_earned_income', 'Other Earned Income', 'numeric', NULL, false, 'Line 1h', 'Other earned income', 37),
('1040', 'combat_pay_election', 'Nontaxable Combat Pay Election', 'numeric', NULL, false, 'Line 1i', 'Combat pay for EIC', 38),
('1040', 'total_line_1', 'Total Income Line 1', 'numeric', NULL, false, 'Line 1z', 'Sum of 1a-1h', 39),
('1040', 'tax_exempt_interest', 'Tax-Exempt Interest', 'numeric', NULL, false, 'Line 2a', 'From 1099-INT Box 8', 40),
('1040', 'taxable_interest', 'Taxable Interest', 'numeric', NULL, false, 'Line 2b', 'From Schedule B', 41),
('1040', 'qualified_dividends', 'Qualified Dividends', 'numeric', NULL, false, 'Line 3a', 'From 1099-DIV Box 1b', 42),
('1040', 'ordinary_dividends', 'Ordinary Dividends', 'numeric', NULL, false, 'Line 3b', 'From Schedule B', 43),
('1040', 'ira_distributions', 'IRA Distributions', 'numeric', NULL, false, 'Line 4a', 'Total IRA distributions', 44),
('1040', 'ira_taxable', 'IRA Taxable Amount', 'numeric', NULL, false, 'Line 4b', 'Taxable amount', 45),
('1040', 'pensions_annuities', 'Pensions and Annuities', 'numeric', NULL, false, 'Line 5a', 'Total pensions', 46),
('1040', 'pensions_taxable', 'Pensions Taxable Amount', 'numeric', NULL, false, 'Line 5b', 'Taxable amount', 47),
('1040', 'social_security_benefits', 'Social Security Benefits', 'numeric', NULL, false, 'Line 6a', 'Total SS benefits', 48),
('1040', 'social_security_taxable', 'SS Taxable Amount', 'numeric', NULL, false, 'Line 6b', 'Taxable amount', 49),
('1040', 'capital_gain_loss', 'Capital Gain or Loss', 'numeric', NULL, false, 'Line 7', 'From Schedule D', 50),
('1040', 'schedule_1_income', 'Additional Income', 'numeric', NULL, false, 'Line 8', 'From Schedule 1', 51),
('1040', 'total_income', 'Total Income', 'numeric', NULL, false, 'Line 9', 'Sum of lines 1z-8', 52),
('1040', 'schedule_1_adjustments', 'Adjustments to Income', 'numeric', NULL, false, 'Line 10', 'From Schedule 1', 53),
('1040', 'adjusted_gross_income', 'Adjusted Gross Income', 'numeric', NULL, false, 'Line 11', 'Line 9 minus line 10', 54),
-- Deductions
('1040', 'standard_deduction', 'Standard Deduction', 'numeric', NULL, false, 'Line 12', 'Standard or itemized', 55),
('1040', 'qbi_deduction', 'QBI Deduction', 'numeric', NULL, false, 'Line 13', 'From Form 8995', 56),
('1040', 'total_deductions', 'Total Deductions', 'numeric', NULL, false, 'Line 14', 'Lines 12 + 13', 57),
('1040', 'taxable_income', 'Taxable Income', 'numeric', NULL, false, 'Line 15', 'Line 11 minus 14', 58),
-- Tax and Credits
('1040', 'tax', 'Tax', 'numeric', NULL, false, 'Line 16', 'From Tax Table or Schedule', 59),
('1040', 'schedule_2_tax', 'Additional Tax', 'numeric', NULL, false, 'Line 17', 'From Schedule 2', 60),
('1040', 'total_tax_before_credits', 'Total Tax Before Credits', 'numeric', NULL, false, 'Line 18', 'Lines 16 + 17', 61),
('1040', 'child_tax_credit', 'Child Tax Credit', 'numeric', NULL, false, 'Line 19', 'From Schedule 8812', 62),
('1040', 'schedule_3_credits', 'Other Credits', 'numeric', NULL, false, 'Line 20', 'From Schedule 3', 63),
('1040', 'total_credits', 'Total Credits', 'numeric', NULL, false, 'Line 21', 'Lines 19 + 20', 64),
('1040', 'tax_after_credits', 'Tax After Credits', 'numeric', NULL, false, 'Line 22', 'Line 18 minus 21', 65),
('1040', 'other_taxes', 'Other Taxes', 'numeric', NULL, false, 'Line 23', 'From Schedule 2', 66),
('1040', 'total_tax', 'Total Tax', 'numeric', NULL, false, 'Line 24', 'Lines 22 + 23', 67),
-- Payments
('1040', 'federal_withheld', 'Federal Tax Withheld', 'numeric', NULL, false, 'Line 25a', 'From W-2s', 68),
('1040', 'form_1099_withheld', 'Form 1099 Withheld', 'numeric', NULL, false, 'Line 25b', 'From 1099s', 69),
('1040', 'other_withheld', 'Other Withholding', 'numeric', NULL, false, 'Line 25c', 'Other withholding', 70),
('1040', 'estimated_payments', 'Estimated Tax Payments', 'numeric', NULL, false, 'Line 26', '2024 estimated payments', 71),
('1040', 'earned_income_credit', 'Earned Income Credit', 'numeric', NULL, false, 'Line 27', 'EIC amount', 72),
('1040', 'additional_child_credit', 'Additional Child Tax Credit', 'numeric', NULL, false, 'Line 28', 'Refundable CTC', 73),
('1040', 'american_opportunity_credit', 'American Opportunity Credit', 'numeric', NULL, false, 'Line 29', 'Education credit', 74),
('1040', 'schedule_3_payments', 'Other Payments', 'numeric', NULL, false, 'Line 31', 'From Schedule 3', 75),
('1040', 'total_payments', 'Total Payments', 'numeric', NULL, false, 'Line 33', 'Sum of payment lines', 76),
-- Refund/Amount Owed
('1040', 'overpaid', 'Amount Overpaid', 'numeric', NULL, false, 'Line 34', 'If payments > tax', 77),
('1040', 'refund_amount', 'Refund Amount', 'numeric', NULL, false, 'Line 35a', 'Amount to be refunded', 78),
('1040', 'routing_number', 'Routing Number', 'text', 9, false, 'Line 35b', 'Bank routing number', 79),
('1040', 'account_type', 'Account Type', 'enum', 1, false, 'Line 35c', 'C=Checking, S=Savings', 80),
('1040', 'account_number', 'Account Number', 'text', 17, false, 'Line 35d', 'Bank account number', 81),
('1040', 'applied_to_next_year', 'Applied to Next Year', 'numeric', NULL, false, 'Line 36', 'Amount to apply to next year', 82),
('1040', 'amount_owed', 'Amount You Owe', 'numeric', NULL, false, 'Line 37', 'If tax > payments', 83),
('1040', 'estimated_tax_penalty', 'Estimated Tax Penalty', 'numeric', NULL, false, 'Line 38', 'Underpayment penalty', 84);

-- Insert Form 1040-X (Amended Return) field definitions
INSERT INTO public.irs_form_field_definitions (form_type, field_name, field_label, field_type, max_length, is_required, irs_box_number, description, display_order) VALUES
('1040-X', 'calendar_year', 'Calendar Year Being Amended', 'text', 4, true, NULL, 'Year of return being amended', 1),
('1040-X', 'first_name', 'Your First Name', 'text', 40, true, NULL, 'First name', 2),
('1040-X', 'last_name', 'Your Last Name', 'text', 40, true, NULL, 'Last name', 3),
('1040-X', 'ssn', 'Your SSN', 'text', 9, true, NULL, 'Social Security Number', 4),
('1040-X', 'spouse_ssn', 'Spouse SSN', 'text', 9, false, NULL, 'If joint return', 5),
('1040-X', 'address', 'Current Home Address', 'text', 40, true, NULL, 'Street address', 6),
('1040-X', 'city_state_zip', 'City, State, ZIP', 'text', 60, true, NULL, 'City, state, and ZIP', 7),
('1040-X', 'filing_status_original', 'Original Filing Status', 'enum', 1, true, NULL, 'Status on original return', 8),
('1040-X', 'filing_status_amended', 'Amended Filing Status', 'enum', 1, false, NULL, 'New filing status if changed', 9),
-- Column A - Original
('1040-X', 'agi_original', 'AGI - Original', 'numeric', NULL, false, 'Line 1 Col A', 'Original AGI', 10),
('1040-X', 'itemized_or_standard_original', 'Deductions - Original', 'numeric', NULL, false, 'Line 2 Col A', 'Original deductions', 11),
('1040-X', 'exemptions_original', 'Exemptions - Original', 'numeric', NULL, false, 'Line 3 Col A', 'Original exemptions', 12),
('1040-X', 'taxable_income_original', 'Taxable Income - Original', 'numeric', NULL, false, 'Line 5 Col A', 'Original taxable income', 13),
('1040-X', 'tax_original', 'Tax - Original', 'numeric', NULL, false, 'Line 6 Col A', 'Original tax', 14),
('1040-X', 'credits_original', 'Credits - Original', 'numeric', NULL, false, 'Line 7 Col A', 'Original credits', 15),
-- Column B - Net Change
('1040-X', 'agi_change', 'AGI - Net Change', 'numeric', NULL, false, 'Line 1 Col B', 'Change in AGI', 16),
('1040-X', 'deductions_change', 'Deductions - Net Change', 'numeric', NULL, false, 'Line 2 Col B', 'Change in deductions', 17),
('1040-X', 'taxable_income_change', 'Taxable Income - Net Change', 'numeric', NULL, false, 'Line 5 Col B', 'Change in taxable income', 18),
('1040-X', 'tax_change', 'Tax - Net Change', 'numeric', NULL, false, 'Line 6 Col B', 'Change in tax', 19),
-- Column C - Correct Amount
('1040-X', 'agi_corrected', 'AGI - Corrected', 'numeric', NULL, false, 'Line 1 Col C', 'Corrected AGI', 20),
('1040-X', 'deductions_corrected', 'Deductions - Corrected', 'numeric', NULL, false, 'Line 2 Col C', 'Corrected deductions', 21),
('1040-X', 'taxable_income_corrected', 'Taxable Income - Corrected', 'numeric', NULL, false, 'Line 5 Col C', 'Corrected taxable income', 22),
('1040-X', 'tax_corrected', 'Tax - Corrected', 'numeric', NULL, false, 'Line 6 Col C', 'Corrected tax', 23),
('1040-X', 'credits_corrected', 'Credits - Corrected', 'numeric', NULL, false, 'Line 7 Col C', 'Corrected credits', 24),
-- Payments and Refund
('1040-X', 'total_tax_liability', 'Total Tax Liability', 'numeric', NULL, false, 'Line 10', 'From line 6 Col C', 25),
('1040-X', 'total_payments', 'Total Payments', 'numeric', NULL, false, 'Line 12', 'Payments plus refundable credits', 26),
('1040-X', 'overpayment', 'Overpayment', 'numeric', NULL, false, 'Line 14', 'If payments > tax', 27),
('1040-X', 'amount_owed', 'Amount You Owe', 'numeric', NULL, false, 'Line 17', 'If tax > payments', 28),
-- Explanation
('1040-X', 'explanation', 'Explanation of Changes', 'text', 2000, true, 'Part III', 'Explain each change', 29);

-- Insert Schedule C field definitions  
INSERT INTO public.irs_form_field_definitions (form_type, field_name, field_label, field_type, max_length, is_required, irs_box_number, description, display_order) VALUES
('Schedule C', 'business_name', 'Business Name', 'text', 75, false, 'Line A', 'Principal business or profession', 1),
('Schedule C', 'principal_business_code', 'Business Code', 'text', 6, true, 'Line B', 'From IRS instructions', 2),
('Schedule C', 'business_address', 'Business Address', 'text', 40, false, 'Line C', 'If different from home', 3),
('Schedule C', 'ein', 'Employer ID Number', 'text', 9, false, 'Line D', 'If you have employees', 4),
('Schedule C', 'accounting_method', 'Accounting Method', 'enum', 1, true, 'Line F', '1=Cash, 2=Accrual, 3=Other', 5),
('Schedule C', 'materially_participated', 'Material Participation', 'boolean', NULL, true, 'Line G', 'Did you materially participate?', 6),
('Schedule C', 'started_or_acquired', 'Started or Acquired', 'boolean', NULL, false, 'Line H', 'Did you start or acquire in 2024?', 7),
('Schedule C', 'made_payments_1099', 'Made Payments Requiring 1099', 'boolean', NULL, false, 'Line I', 'Required to file 1099s?', 8),
('Schedule C', 'filed_1099s', 'Filed Required 1099s', 'boolean', NULL, false, 'Line J', 'Did you file required 1099s?', 9),
-- Income
('Schedule C', 'gross_receipts', 'Gross Receipts or Sales', 'numeric', NULL, true, 'Line 1', 'Total income', 10),
('Schedule C', 'returns_allowances', 'Returns and Allowances', 'numeric', NULL, false, 'Line 2', 'Refunds, etc.', 11),
('Schedule C', 'cost_of_goods_sold', 'Cost of Goods Sold', 'numeric', NULL, false, 'Line 4', 'From line 42', 12),
('Schedule C', 'gross_profit', 'Gross Profit', 'numeric', NULL, false, 'Line 5', 'Line 3 minus line 4', 13),
('Schedule C', 'other_income', 'Other Income', 'numeric', NULL, false, 'Line 6', 'Including gas tax credit', 14),
('Schedule C', 'gross_income', 'Gross Income', 'numeric', NULL, false, 'Line 7', 'Lines 5 + 6', 15),
-- Expenses Part II
('Schedule C', 'advertising', 'Advertising', 'numeric', NULL, false, 'Line 8', 'Advertising expense', 16),
('Schedule C', 'car_truck_expenses', 'Car and Truck Expenses', 'numeric', NULL, false, 'Line 9', 'From Form 4562 or actual', 17),
('Schedule C', 'commissions_fees', 'Commissions and Fees', 'numeric', NULL, false, 'Line 10', 'Commissions paid', 18),
('Schedule C', 'contract_labor', 'Contract Labor', 'numeric', NULL, false, 'Line 11', 'Payments to contractors', 19),
('Schedule C', 'depletion', 'Depletion', 'numeric', NULL, false, 'Line 12', 'Depletion expense', 20),
('Schedule C', 'depreciation', 'Depreciation', 'numeric', NULL, false, 'Line 13', 'From Form 4562', 21),
('Schedule C', 'employee_benefits', 'Employee Benefit Programs', 'numeric', NULL, false, 'Line 14', 'Health insurance, etc.', 22),
('Schedule C', 'insurance', 'Insurance (other than health)', 'numeric', NULL, false, 'Line 15', 'Business insurance', 23),
('Schedule C', 'interest_mortgage', 'Interest - Mortgage', 'numeric', NULL, false, 'Line 16a', 'Mortgage interest', 24),
('Schedule C', 'interest_other', 'Interest - Other', 'numeric', NULL, false, 'Line 16b', 'Other interest', 25),
('Schedule C', 'legal_professional', 'Legal and Professional Services', 'numeric', NULL, false, 'Line 17', 'Attorney, accountant fees', 26),
('Schedule C', 'office_expense', 'Office Expense', 'numeric', NULL, false, 'Line 18', 'Office supplies', 27),
('Schedule C', 'pension_profit_sharing', 'Pension and Profit-Sharing', 'numeric', NULL, false, 'Line 19', 'Retirement contributions', 28),
('Schedule C', 'rent_vehicles', 'Rent - Vehicles/Equipment', 'numeric', NULL, false, 'Line 20a', 'Vehicle/equipment rental', 29),
('Schedule C', 'rent_other', 'Rent - Other Business Property', 'numeric', NULL, false, 'Line 20b', 'Office/building rent', 30),
('Schedule C', 'repairs_maintenance', 'Repairs and Maintenance', 'numeric', NULL, false, 'Line 21', 'Repairs expense', 31),
('Schedule C', 'supplies', 'Supplies', 'numeric', NULL, false, 'Line 22', 'Supplies not in COGS', 32),
('Schedule C', 'taxes_licenses', 'Taxes and Licenses', 'numeric', NULL, false, 'Line 23', 'Business taxes', 33),
('Schedule C', 'travel', 'Travel', 'numeric', NULL, false, 'Line 24a', 'Travel expense', 34),
('Schedule C', 'meals', 'Deductible Meals', 'numeric', NULL, false, 'Line 24b', '50% of meal expenses', 35),
('Schedule C', 'utilities', 'Utilities', 'numeric', NULL, false, 'Line 25', 'Utility expense', 36),
('Schedule C', 'wages', 'Wages', 'numeric', NULL, false, 'Line 26', 'Employee wages', 37),
('Schedule C', 'other_expenses', 'Other Expenses', 'numeric', NULL, false, 'Line 27a', 'From line 48', 38),
('Schedule C', 'total_expenses', 'Total Expenses', 'numeric', NULL, false, 'Line 28', 'Sum of expenses', 39),
('Schedule C', 'tentative_profit_loss', 'Tentative Profit or Loss', 'numeric', NULL, false, 'Line 29', 'Line 7 minus 28', 40),
('Schedule C', 'home_office_deduction', 'Home Office Deduction', 'numeric', NULL, false, 'Line 30', 'From Form 8829', 41),
('Schedule C', 'net_profit_loss', 'Net Profit or Loss', 'numeric', NULL, false, 'Line 31', 'Line 29 minus 30', 42);

-- Insert W-2 field definitions
INSERT INTO public.irs_form_field_definitions (form_type, field_name, field_label, field_type, max_length, is_required, irs_box_number, description, display_order) VALUES
('W-2', 'employee_ssn', 'Employee SSN', 'text', 9, true, 'Box a', 'Social Security Number', 1),
('W-2', 'ein', 'Employer EIN', 'text', 9, true, 'Box b', 'Employer ID Number', 2),
('W-2', 'employer_name', 'Employer Name', 'text', 75, true, 'Box c', 'Employer name', 3),
('W-2', 'employer_address', 'Employer Address', 'text', 100, true, 'Box c', 'Full address', 4),
('W-2', 'control_number', 'Control Number', 'text', 20, false, 'Box d', 'Employer use only', 5),
('W-2', 'employee_first_name', 'Employee First Name', 'text', 40, true, 'Box e', 'First name', 6),
('W-2', 'employee_middle_initial', 'Employee MI', 'text', 1, false, 'Box e', 'Middle initial', 7),
('W-2', 'employee_last_name', 'Employee Last Name', 'text', 40, true, 'Box e', 'Last name', 8),
('W-2', 'employee_suffix', 'Employee Suffix', 'text', 10, false, 'Box e', 'Jr, Sr, etc.', 9),
('W-2', 'employee_address', 'Employee Address', 'text', 100, true, 'Box f', 'Full address', 10),
('W-2', 'wages_tips', 'Wages, Tips, Other Compensation', 'numeric', NULL, true, 'Box 1', 'Taxable wages', 11),
('W-2', 'federal_withheld', 'Federal Income Tax Withheld', 'numeric', NULL, false, 'Box 2', 'Federal tax withheld', 12),
('W-2', 'ss_wages', 'Social Security Wages', 'numeric', NULL, false, 'Box 3', 'SS taxable wages', 13),
('W-2', 'ss_tax_withheld', 'Social Security Tax Withheld', 'numeric', NULL, false, 'Box 4', 'SS tax withheld', 14),
('W-2', 'medicare_wages', 'Medicare Wages and Tips', 'numeric', NULL, false, 'Box 5', 'Medicare taxable wages', 15),
('W-2', 'medicare_tax_withheld', 'Medicare Tax Withheld', 'numeric', NULL, false, 'Box 6', 'Medicare tax withheld', 16),
('W-2', 'ss_tips', 'Social Security Tips', 'numeric', NULL, false, 'Box 7', 'Tips subject to SS', 17),
('W-2', 'allocated_tips', 'Allocated Tips', 'numeric', NULL, false, 'Box 8', 'Allocated tips', 18),
('W-2', 'dependent_care', 'Dependent Care Benefits', 'numeric', NULL, false, 'Box 10', 'DCB amount', 19),
('W-2', 'nonqualified_plans', 'Nonqualified Plans', 'numeric', NULL, false, 'Box 11', 'NQDC distributions', 20),
('W-2', 'code_12a', 'Box 12a Code', 'text', 2, false, 'Box 12a', 'See W-2 instructions', 21),
('W-2', 'amount_12a', 'Box 12a Amount', 'numeric', NULL, false, 'Box 12a', 'Amount for code', 22),
('W-2', 'code_12b', 'Box 12b Code', 'text', 2, false, 'Box 12b', 'See W-2 instructions', 23),
('W-2', 'amount_12b', 'Box 12b Amount', 'numeric', NULL, false, 'Box 12b', 'Amount for code', 24),
('W-2', 'code_12c', 'Box 12c Code', 'text', 2, false, 'Box 12c', 'See W-2 instructions', 25),
('W-2', 'amount_12c', 'Box 12c Amount', 'numeric', NULL, false, 'Box 12c', 'Amount for code', 26),
('W-2', 'code_12d', 'Box 12d Code', 'text', 2, false, 'Box 12d', 'See W-2 instructions', 27),
('W-2', 'amount_12d', 'Box 12d Amount', 'numeric', NULL, false, 'Box 12d', 'Amount for code', 28),
('W-2', 'statutory_employee', 'Statutory Employee', 'boolean', NULL, false, 'Box 13', 'Check if applicable', 29),
('W-2', 'retirement_plan', 'Retirement Plan', 'boolean', NULL, false, 'Box 13', 'Check if participant', 30),
('W-2', 'third_party_sick_pay', 'Third-Party Sick Pay', 'boolean', NULL, false, 'Box 13', 'Check if applicable', 31),
('W-2', 'other_14', 'Other (Box 14)', 'text', 100, false, 'Box 14', 'Other compensation info', 32),
('W-2', 'state_1', 'State 1', 'text', 2, false, 'Box 15', 'First state code', 33),
('W-2', 'state_id_1', 'State Employer ID 1', 'text', 20, false, 'Box 15', 'State employer ID', 34),
('W-2', 'state_wages_1', 'State Wages 1', 'numeric', NULL, false, 'Box 16', 'State taxable wages', 35),
('W-2', 'state_tax_1', 'State Tax Withheld 1', 'numeric', NULL, false, 'Box 17', 'State tax withheld', 36),
('W-2', 'local_wages_1', 'Local Wages 1', 'numeric', NULL, false, 'Box 18', 'Local taxable wages', 37),
('W-2', 'local_tax_1', 'Local Tax Withheld 1', 'numeric', NULL, false, 'Box 19', 'Local tax withheld', 38),
('W-2', 'locality_1', 'Locality Name 1', 'text', 20, false, 'Box 20', 'Locality name', 39);

-- Insert W-4 field definitions
INSERT INTO public.irs_form_field_definitions (form_type, field_name, field_label, field_type, max_length, is_required, irs_box_number, description, display_order) VALUES
('W-4', 'first_name', 'First Name', 'text', 40, true, 'Step 1a', 'First name and middle initial', 1),
('W-4', 'last_name', 'Last Name', 'text', 40, true, 'Step 1a', 'Last name', 2),
('W-4', 'ssn', 'Social Security Number', 'text', 9, true, 'Step 1b', 'Your SSN', 3),
('W-4', 'address', 'Home Address', 'text', 40, true, 'Step 1c', 'Street address', 4),
('W-4', 'city_state_zip', 'City, State, ZIP', 'text', 60, true, 'Step 1c', 'City, state, and ZIP', 5),
('W-4', 'filing_status', 'Filing Status', 'enum', 1, true, 'Step 1c', 'S=Single/MFS, M=MFJ, H=HOH', 6),
('W-4', 'multiple_jobs', 'Multiple Jobs Worksheet', 'boolean', NULL, false, 'Step 2a', 'Check if applicable', 7),
('W-4', 'spouse_works', 'Spouse Works', 'boolean', NULL, false, 'Step 2c', 'Check if MFJ and spouse works', 8),
('W-4', 'qualifying_children', 'Number of Qualifying Children', 'numeric', NULL, false, 'Step 3', 'Under 17 at year end', 9),
('W-4', 'other_dependents', 'Number of Other Dependents', 'numeric', NULL, false, 'Step 3', 'Other dependents', 10),
('W-4', 'dependent_credit', 'Total Dependent Credit', 'numeric', NULL, false, 'Step 3', 'Calculated credit amount', 11),
('W-4', 'other_income', 'Other Income', 'numeric', NULL, false, 'Step 4a', 'Not from jobs', 12),
('W-4', 'deductions', 'Deductions', 'numeric', NULL, false, 'Step 4b', 'If itemizing', 13),
('W-4', 'extra_withholding', 'Extra Withholding', 'numeric', NULL, false, 'Step 4c', 'Additional per paycheck', 14);

-- Insert W-9 field definitions
INSERT INTO public.irs_form_field_definitions (form_type, field_name, field_label, field_type, max_length, is_required, irs_box_number, description, display_order) VALUES
('W-9', 'name', 'Name', 'text', 75, true, 'Line 1', 'Name as shown on tax return', 1),
('W-9', 'business_name', 'Business Name', 'text', 75, false, 'Line 2', 'If different from line 1', 2),
('W-9', 'tax_classification', 'Federal Tax Classification', 'enum', 1, true, 'Line 3', 'Entity type code', 3),
('W-9', 'llc_classification', 'LLC Tax Classification', 'text', 1, false, 'Line 3', 'C, S, or P for partnership', 4),
('W-9', 'exempt_payee_code', 'Exempt Payee Code', 'text', 2, false, 'Line 4', 'If exempt from backup withholding', 5),
('W-9', 'fatca_exemption_code', 'FATCA Exemption Code', 'text', 2, false, 'Line 4', 'If exempt from FATCA', 6),
('W-9', 'address', 'Address', 'text', 40, true, 'Line 5', 'Street address', 7),
('W-9', 'city_state_zip', 'City, State, ZIP', 'text', 60, true, 'Line 6', 'City, state, and ZIP', 8),
('W-9', 'account_numbers', 'Account Numbers', 'text', 40, false, 'Line 7', 'Optional requester info', 9),
('W-9', 'ssn', 'Social Security Number', 'text', 9, false, 'Part I', 'If individual', 10),
('W-9', 'ein', 'Employer ID Number', 'text', 9, false, 'Part I', 'If business', 11);

-- Insert common state tax forms
INSERT INTO public.state_tax_forms (state_code, state_name, form_type, form_number, form_name, filing_deadline, has_local_tax) VALUES
('AL', 'Alabama', 'individual', '40', 'Individual Income Tax Return', 'April 15', false),
('AK', 'Alaska', 'individual', 'N/A', 'No State Income Tax', NULL, false),
('AZ', 'Arizona', 'individual', '140', 'Resident Personal Income Tax Return', 'April 15', false),
('AR', 'Arkansas', 'individual', 'AR1000F', 'Individual Income Tax Return', 'April 15', false),
('CA', 'California', 'individual', '540', 'California Resident Income Tax Return', 'April 15', false),
('CO', 'Colorado', 'individual', 'DR 0104', 'Colorado Individual Income Tax Return', 'April 15', true),
('CT', 'Connecticut', 'individual', 'CT-1040', 'Connecticut Resident Income Tax Return', 'April 15', false),
('DE', 'Delaware', 'individual', '200-01', 'Resident Individual Income Tax Return', 'April 30', true),
('FL', 'Florida', 'individual', 'N/A', 'No State Income Tax', NULL, false),
('GA', 'Georgia', 'individual', '500', 'Individual Income Tax Return', 'April 15', false),
('HI', 'Hawaii', 'individual', 'N-11', 'Individual Income Tax Return - Resident', 'April 20', false),
('ID', 'Idaho', 'individual', '40', 'Idaho Individual Income Tax Return', 'April 15', false),
('IL', 'Illinois', 'individual', 'IL-1040', 'Individual Income Tax Return', 'April 15', false),
('IN', 'Indiana', 'individual', 'IT-40', 'Indiana Full-Year Resident Individual Income Tax Return', 'April 15', true),
('IA', 'Iowa', 'individual', 'IA 1040', 'Iowa Individual Income Tax Return', 'April 30', false),
('KS', 'Kansas', 'individual', 'K-40', 'Kansas Individual Income Tax Return', 'April 15', false),
('KY', 'Kentucky', 'individual', '740', 'Kentucky Individual Income Tax Return', 'April 15', true),
('LA', 'Louisiana', 'individual', 'IT-540', 'Louisiana Resident Income Tax Return', 'May 15', false),
('ME', 'Maine', 'individual', '1040ME', 'Maine Individual Income Tax Return', 'April 15', false),
('MD', 'Maryland', 'individual', '502', 'Maryland Resident Income Tax Return', 'April 15', true),
('MA', 'Massachusetts', 'individual', '1', 'Massachusetts Resident Income Tax Return', 'April 15', false),
('MI', 'Michigan', 'individual', 'MI-1040', 'Michigan Individual Income Tax Return', 'April 15', true),
('MN', 'Minnesota', 'individual', 'M1', 'Minnesota Individual Income Tax Return', 'April 15', false),
('MS', 'Mississippi', 'individual', '80-105', 'Mississippi Resident Individual Income Tax Return', 'April 15', false),
('MO', 'Missouri', 'individual', 'MO-1040', 'Missouri Individual Income Tax Return', 'April 15', true),
('MT', 'Montana', 'individual', '2', 'Montana Individual Income Tax Return', 'April 15', false),
('NE', 'Nebraska', 'individual', '1040N', 'Nebraska Individual Income Tax Return', 'April 15', false),
('NV', 'Nevada', 'individual', 'N/A', 'No State Income Tax', NULL, false),
('NH', 'New Hampshire', 'individual', 'DP-10', 'Interest and Dividends Tax Return', 'April 15', false),
('NJ', 'New Jersey', 'individual', 'NJ-1040', 'New Jersey Resident Income Tax Return', 'April 15', false),
('NM', 'New Mexico', 'individual', 'PIT-1', 'Personal Income Tax Return', 'April 15', false),
('NY', 'New York', 'individual', 'IT-201', 'Resident Income Tax Return', 'April 15', true),
('NC', 'North Carolina', 'individual', 'D-400', 'Individual Income Tax Return', 'April 15', false),
('ND', 'North Dakota', 'individual', 'ND-1', 'Individual Income Tax Return', 'April 15', false),
('OH', 'Ohio', 'individual', 'IT 1040', 'Ohio Individual Income Tax Return', 'April 15', true),
('OK', 'Oklahoma', 'individual', '511', 'Oklahoma Resident Individual Income Tax Return', 'April 15', false),
('OR', 'Oregon', 'individual', '40', 'Oregon Individual Income Tax Return', 'April 15', true),
('PA', 'Pennsylvania', 'individual', 'PA-40', 'Pennsylvania Income Tax Return', 'April 15', true),
('RI', 'Rhode Island', 'individual', 'RI-1040', 'Rhode Island Resident Individual Income Tax Return', 'April 15', false),
('SC', 'South Carolina', 'individual', 'SC1040', 'South Carolina Individual Income Tax Return', 'April 15', false),
('SD', 'South Dakota', 'individual', 'N/A', 'No State Income Tax', NULL, false),
('TN', 'Tennessee', 'individual', 'N/A', 'No State Income Tax (Hall Tax ended 2021)', NULL, false),
('TX', 'Texas', 'individual', 'N/A', 'No State Income Tax', NULL, false),
('UT', 'Utah', 'individual', 'TC-40', 'Utah Individual Income Tax Return', 'April 15', false),
('VT', 'Vermont', 'individual', 'IN-111', 'Vermont Income Tax Return', 'April 15', false),
('VA', 'Virginia', 'individual', '760', 'Virginia Resident Individual Income Tax Return', 'May 1', false),
('WA', 'Washington', 'individual', 'N/A', 'No State Income Tax', NULL, false),
('WV', 'West Virginia', 'individual', 'IT-140', 'West Virginia Personal Income Tax Return', 'April 15', true),
('WI', 'Wisconsin', 'individual', '1', 'Wisconsin Income Tax Return', 'April 15', false),
('WY', 'Wyoming', 'individual', 'N/A', 'No State Income Tax', NULL, false),
('DC', 'District of Columbia', 'individual', 'D-40', 'DC Individual Income Tax Return', 'April 15', false);